remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

baseurl: "/PostgreSQL_Notes/" # the subpath of your site, e.g. /blog
url: "https://kellen-linse.github.io/" # the base hostname & protocol for your site, e.g. http://example.com